.POSIX:
.PHONY: common
common:
	@echo "GNU Make is required to test. use gmake instead if present"
clean: common
fclean: common
re: common
refresh: common
test: common
.PHONY: all clean fclean re refresh test
