all:
	@echo "GNU Make is required to test"
clean:
	@echo "GNU Make is required to test"
fclean:
	@echo "GNU Make is required to test"
re:
	@echo "GNU Make is required to test"
refresh:
	@echo "GNU Make is required to test"
test:
	@echo "GNU Make is required to test"
.PHONY: all clean fclean re refresh test
