.POSIX:
.PHONY: common
common:
	@echo "GNU Make is required to test. use gmake instead if present"
all: common
clean: common
fclean: common
re: common
refresh: common
retest: common
test: common
.PHONY: all clean fclean re refresh retest test
